site_name: Agent Rebel
site_description: Agent Rebel / shim to use agent rebel with LLMs
site_url: https://github.com/agent-rebel

copyright: Copyright &copy; 2025 Matthias Rebel

strict: true
docs_dir: docs

repo_name: agent-rebel
repo_url: https://github.com/agent-rebel

nav:
  - Introduction: index.md
  # - install.md
  # - help.md
  #  - troubleshooting.md
  - changelog.md
  - Projects:
      - projects/resume-as-code.md
      - Vibe Coding Journey: projects/ai-coding-assistents.md
      # - Dialogues:
      #     - dialogues/dialogue1-2025-05-22.md
      #     - dialogues/dialogue2-2025-05-23.md
      # - projects/fastfourier.md
      - Dominique: projects/dominique.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: "Switch to system preference"
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - navigation.footer
  # logo: "img/logo-white.svg"
  favicon: "favicon.ico"
  #custom_dir: overrides
extra_css:
  - styles/main-bg.css
  - styles/extra.css
  - styles/portfolio.css
  - styles/agents.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  # - llmstxt:
  #   markdown_description: Long description of my project.
  #   sections:
  #     Usage documentation:
  #       - file1.md
  #       - file2.md
  # - exclude:
  #   glob:
  #     - "docs/resume/node_modules**"
  #     - "docs/resume/.env"

exclude_docs: |
  resume
  resume2
  resume/node_modules/
  .env

extra:
  # hide the "Made with Material for MkDocs" message
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rebeling
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthias-rebel-525b3333
    - icon: fontawesome/solid/envelope
      link: mailto:matthias.rebel@gmail.com
